### PR TITLE
Local builders, console mode, rpath policy check...

### PR DESCRIPTION
**Pull request by korli**
I have these changes for some time in my fork. I've using this to build mass updates on x86_64. Though I didn't test with remote slaves, there should be no impact.

Typical command line parameters: 
--build-master --local-builders=8 --console --update-dependencies -G -S (list of packages to be produced)

Please don't squash commits on PR merge.

### CODE REVIEW

**Comment by waddlesplash** [comment]
Did a quick glance through the code, looks OK to me. Feel free to merge, if nobody else has any comments.

**Comment by kallisti5** [comment]
On 2016-12-18 08:53, Jérôme Duval wrote:
> I have these changes for some time in my fork. I've using this to
> build mass updates on x86_64. Though I didn't test with remote slaves,
> there should be no impact.
> 
> Typical command line parameters:
> --build-master --local-builders=8 --console --update-dependencies -G
> -S (list of packages to be produced)
> 
> Please don't squash commits on PR merge.
> -------------------------
> 
> YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
> 
>   https://github.com/haikuports/haikuporter/pull/107
> 
> COMMIT SUMMARY
> 
>  	* Implement local builders.
>  	* Add a console mode.
>  	* Add option --update-dependencies
>  	* BuildMaster: init buildStatus, dump output for CalledProcessError
>  	* Policy: check RPATH when searching libs in the package.

https://github.com/haikuports/haikuporter/commit/68e3958c02b5cb92fb6c6511b53bcb745a739019

So, this seems likely to have broken the remote builder logs.

Example:
http://pulkomandy.tk/~pulkomandy/output/builds/12098.log

All the output of the running remote haikuporter is missing.
Everything works until haikuporter begins to run, then the remote output 
is blank.

Do you have any idea what the cause might be? Maybe the new logging
doesn't detect a pty and hides output or something?

  -- Alex

**Comment by korli** [comment]
It seems like Pulkomandy committed a fix in 09dea6b.

**Comment by pulkomandy** [comment]
Yes, that fixed it.

**Pull request merged**
