### PR TITLE
increase maximum allowed length of SUMMARY to 100

### PR DESCRIPTION
**Pull request by jmairboeck**
this was discussed in haikuports/haikuports#6353

it came up here: https://github.com/haikuports/haikuports/pull/6229#discussion_r780248489

### CODE REVIEW

**Comment by Begasus** [comment]
As mentioned in the comments there, I'm not sure that for SUMMARY we should extend this to 100 characters (just my 2 cents) :)

**Comment by jmairboeck** [comment]
If this should not be changed, we can also close this. This is just a suggestion.

**Comment by Begasus** [comment]
Let's wait what others have to say about it, it's good to bring this up :+1:

**Comment by humdingerb** [comment]
I agree to keep the limit of the SUMMARY. Its intention is to keep the summary short and succinct. That also ensures that the summary column in HaikuDepot can be kept nice and narrow.

**Comment by Begasus** [comment]
I mentioned this too in the comments, in FileTypes I think it would look a bit overkill (when used in rdefs) :)

**Comment by humdingerb** [comment]
Alright, let's keep the SUMMARY max length as is and close this.

**Pull request closed without merging**
