### PR TITLE
Add support for .7z archives

### PR DESCRIPTION
**Pull request by DarkmatterVale**
I _think_ it works :D

### CODE REVIEW

**Comment by waddlesplash** [comment]
Can you try it? :p

**Comment by DarkmatterVale** [comment]
I did, using http://7-zip.org/a/7z1514-src.7z but I get the output "nothing to commit". I think this is an issue with haikuporter, and not the extraction (because haikuporter appears to have extracted the files fine).

**Comment by waddlesplash** [comment]
Sooo can you investigate it?

**Comment by KapiX** [comment]
I think you might be more successful if you unpack the files into `targetBaseDir` instead of `self.workDir`.
Also, use `subdir` like the other unpack methods do.

**Comment by DarkmatterVale** [comment]
I will make the changes. Thank you for the review!!

**Comment by DarkmatterVale** [comment]
Hmmm...So I am having an issue. The log output (when I run a simple test recipe) is:

```
~> hp test_7z
Warning: haiku-apps/tipster-1.0.0        is overruled by duplicate in haiku-apps - please remove one of them
Checking if any package-infos need to be updated ...
Looking for stale dependency-infos ...
Checking if package dependencies need to be updated ...
        updating dependency infos of test_7z-1.0.0
----------------------------------------------------------------------
haiku-apps::test_7z-1.0.0
        /boot/home/haikuports/haiku-apps/test_7z/test_7z-1.0.0.recipe
----------------------------------------------------------------------
Skipping download of source for 7z1514-src.7z
Validating checksum of 7z1514-src.7z
Unpacking source of 7z1514-src.7z
OPENING FILE
FILE OPENED...CREATING ARCHIVE
invalid type '\x19'
~>
```

Any ideas why I am getting a '\x19'?

**Comment by korli** [comment]
Please don't add py7zlib as a hard dependency. This will cause trouble for bootstrapping.

**Comment by mmuman** [comment]
Sorry you'll have to rework this after my last commit.
How about using the 7za command instead so it won't force python to import stuff?

**Comment by waddlesplash** [comment]
superseded by #142

**Pull request closed without merging**
